import { Mongo } from 'meteor/mongo';

export const HSK1 = new Mongo.Collection('hsk1');
if (Meteor.isServer) {
  var hsk1voc = [
    {"level":"HSK1","trad":"愛","simp":"爱","pinyin":"ai4","translation":"to love/to be fond of/to like/affection/to be inclined (to do sth)/to tend to (happen)"},
    {"level":"HSK1","trad":"八","simp":"八","pinyin":"ba1","translation":"eight/8"},
    {"level":"HSK1","trad":"爸爸","simp":"爸爸","pinyin":"ba4 ba5","translation":"(informal) father/CL:個|个[ge4],位[wei4]"},
    {"level":"HSK1","trad":"北京","simp":"北京","pinyin":"Bei3 jing1","translation":"Beijing, capital of People's Republic of China/Peking/PRC government"},
    {"level":"HSK1","trad":"杯子","simp":"杯子","pinyin":"bei1 zi5","translation":"cup/glass/CL:個|个[ge4],隻|只[zhi1]"},
    {"level":"HSK1","trad":"本","simp":"本","pinyin":"ben3","translation":"root/stem/origin/source/this/the current/original/inherent/originally/classifier for books, periodicals, files etc"},
    {"level":"HSK1","trad":"不","simp":"不","pinyin":"bu4","translation":"(negative prefix)/not/no"},
    {"level":"HSK1","trad":"不客氣","simp":"不客气","pinyin":"bu4 ke4 qi5","translation":"you're welcome/don't mention it/impolite/rude/blunt"},
    {"level":"HSK1","trad":"菜","simp":"菜","pinyin":"cai4","translation":"dish (type of food)/vegetable/cuisine/CL:盤|盘[pan2],道[dao4]/(coll.) (one's) type/(of one's skills etc) weak/poor"},
    {"level":"HSK1","trad":"茶","simp":"茶","pinyin":"cha2","translation":"tea/tea plant/CL:杯[bei1],壺|壶[hu2]"},
    {"level":"HSK1","trad":"吃","simp":"吃","pinyin":"chi1","translation":"to eat/to consume/to eat at (a cafeteria etc)/to eradicate/to destroy/to absorb/to suffer/to stammer (Taiwan pr. for this sense is [ji2])"},
    {"level":"HSK1","trad":"出租車","simp":"出租车","pinyin":"chu1 zu1 che1","translation":"taxi/(Taiwan) rental car"},
    {"level":"HSK1","trad":"大","simp":"大","pinyin":"da4","translation":"big/huge/large/major/great/wide/deep/older (than)/oldest/eldest/greatly/very much/(dialect) father/father's elder or younger brother"},
    {"level":"HSK1","trad":"打電話","simp":"打电话","pinyin":"da3 dian4 hua4","translation":"to make a telephone call"},
    {"level":"HSK1","trad":"的","simp":"的","pinyin":"de5","translation":"of/~'s (possessive particle)/(used after an attribute)/(used to form a nominal expression)/(used at the end of a declarative sentence for emphasis)"},
    {"level":"HSK1","trad":"點","simp":"点","pinyin":"dian3","translation":"point/dot/drop/speck/o'clock/point (in space or time)/to draw a dot/to check on a list/to choose/to order (food in a restaurant)/to touch briefly/to hint/to light/to ignite/to pour a liquid drop by drop/(old) one fifth of a two-hour watch 更[geng1]/dot stroke in Chinese characters/classifier for items"},
    {"level":"HSK1","trad":"電腦","simp":"电脑","pinyin":"dian4 nao3","translation":"computer/CL:臺|台[tai2]"},
    {"level":"HSK1","trad":"電視","simp":"电视","pinyin":"dian4 shi4","translation":"television/TV/CL:臺|台[tai2],個|个[ge4]"},
    {"level":"HSK1","trad":"電影","simp":"电影","pinyin":"dian4 ying3","translation":"movie/film/CL:部[bu4],片[pian4],幕[mu4],場|场[chang3]"},
    {"level":"HSK1","trad":"東西","simp":"东西","pinyin":"dong1 xi1","translation":"east and west"},
    {"level":"HSK1","trad":"都","simp":"都","pinyin":"dou1","translation":"all/both/entirely/(used for emphasis) even/already/(not) at all"},
    {"level":"HSK1","trad":"讀","simp":"读","pinyin":"du2","translation":"to read/to study/reading of word (i.e. pronunciation), similar to 拼音[pin1 yin1]"},
    {"level":"HSK1","trad":"對不起","simp":"对不起","pinyin":"dui4 bu5 qi3","translation":"unworthy/to let down/I'm sorry/excuse me/pardon me/if you please/sorry? (please repeat)"},
    {"level":"HSK1","trad":"多","simp":"多","pinyin":"duo1","translation":"many/much/often/a lot of/numerous/more/in excess/how (to what extent)/multi-/Taiwan pr. [duo2] when it means 'how'"},
    {"level":"HSK1","trad":"多少","simp":"多少","pinyin":"duo1 shao5","translation":"how much/how many/which (number)/as much as"},
    {"level":"HSK1","trad":"二","simp":"二","pinyin":"er4","translation":"two/2/(Beijing dialect) stupid"},
    {"level":"HSK1","trad":"兒子","simp":"儿子","pinyin":"er2 zi5","translation":"son"},
    {"level":"HSK1","trad":"飯館","simp":"饭馆","pinyin":"fan4 guan3","translation":"restaurant/CL:家[jia1]"},
    {"level":"HSK1","trad":"飛機","simp":"飞机","pinyin":"fei1 ji1","translation":"airplane/CL:架[jia4]"},
    {"level":"HSK1","trad":"分鐘","simp":"分钟","pinyin":"fen1 zhong1","translation":"minute"},
    {"level":"HSK1","trad":"高興","simp":"高兴","pinyin":"gao1 xing4","translation":"happy/glad/willing (to do sth)/in a cheerful mood"},
    {"level":"HSK1","trad":"個","simp":"个","pinyin":"ge4","translation":"individual/this/that/size/classifier for people or objects in general"},
    {"level":"HSK1","trad":"工作","simp":"工作","pinyin":"gong1 zuo4","translation":"to work/(of a machine) to operate/job/work/task/CL:個|个[ge4],份[fen4],項|项[xiang4]"},
    {"level":"HSK1","trad":"狗","simp":"狗","pinyin":"gou3","translation":"dog/CL:隻|只[zhi1],條|条[tiao2]"},
    {"level":"HSK1","trad":"漢語","simp":"汉语","pinyin":"Han4 yu3","translation":"Chinese language/CL:門|门[men2]"},
    {"level":"HSK1","trad":"好","simp":"好","pinyin":"hao3","translation":"good/well/proper/good to/easy to/very/so/(suffix indicating completion or readiness)/(of two people) close/on intimate terms"},
    {"level":"HSK1","trad":"和","simp":"和","pinyin":"he2","translation":"and/together with/with/sum/union/peace/harmony/Taiwan pr. [han4] when it means 'and' or 'with'"},
    {"level":"HSK1","trad":"喝","simp":"喝","pinyin":"he1","translation":"to drink/My goodness!"},
    {"level":"HSK1","trad":"很","simp":"很","pinyin":"hen3","translation":"(adverb of degree)/quite/very/awfully"},
    {"level":"HSK1","trad":"後面","simp":"后面","pinyin":"hou4 mian4","translation":"rear/back/behind/later/afterwards/also pr. [hou4 mian5]"},
    {"level":"HSK1","trad":"回","simp":"回","pinyin":"hui2","translation":"to circle/to go back/to turn around/to answer/to return/to revolve/Hui ethnic group (Chinese Muslims)/time/classifier for acts of a play/section or chapter (of a classic book)"},
    {"level":"HSK1","trad":"會","simp":"会","pinyin":"hui4","translation":"can/to be possible/to be able to/will/to be likely to/to be sure to/to assemble/to meet/to gather/to see/union/group/association/CL:個|个[ge4]/a moment (Taiwan pr. for this sense is [hui3])"},
    {"level":"HSK1","trad":"火車站","simp":"火车站","pinyin":"huo3 che1 zhan4","translation":"train station"},
    {"level":"HSK1","trad":"幾","simp":"几","pinyin":"ji3","translation":"how much/how many/several/a few"},
    {"level":"HSK1","trad":"家","simp":"家","pinyin":"jia1","translation":"home/family/(polite) my (sister, uncle etc)/classifier for families or businesses/refers to the philosophical schools of pre-Han China/noun suffix for a specialist in some activity, such as a musician or revolutionary, corresponding to English -ist, -er, -ary or -ian/CL:個|个[ge4]"},
    {"level":"HSK1","trad":"叫","simp":"叫","pinyin":"jiao4","translation":"to shout/to call/to order/to ask/to be called/by (indicates agent in the passive mood)"},
    {"level":"HSK1","trad":"今天","simp":"今天","pinyin":"jin1 tian1","translation":"today/at the present/now"},
    {"level":"HSK1","trad":"九","simp":"九","pinyin":"jiu3","translation":"nine/9"},
    {"level":"HSK1","trad":"開","simp":"开","pinyin":"kai1","translation":"to open/to start/to turn on/to boil/to write out (a prescription, check, invoice etc)/to operate (a vehicle)/carat (gold)/abbr. for Kelvin, 開爾文|开尔文[Kai1 er3 wen2]/abbr. for 開本|开本[kai1 ben3], book format"},
    {"level":"HSK1","trad":"看","simp":"看","pinyin":"kan1","translation":"to look after/to take care of/to watch/to guard"},
    {"level":"HSK1","trad":"看見","simp":"看见","pinyin":"kan4 jian4","translation":"to see/to catch sight of"},
    {"level":"HSK1","trad":"塊","simp":"块","pinyin":"kuai4","translation":"lump (of earth)/chunk/piece/classifier for pieces of cloth, cake, soap etc/(coll.) classifier for money and currency units"},
    {"level":"HSK1","trad":"來","simp":"来","pinyin":"lai2","translation":"to come/to arrive/to come round/ever since/next"},
    {"level":"HSK1","trad":"老師","simp":"老师","pinyin":"lao3 shi1","translation":"teacher/CL:個|个[ge4],位[wei4]"},
    {"level":"HSK1","trad":"了","simp":"了","pinyin":"le5","translation":"(modal particle intensifying preceding clause)/(completed action marker)"},
    {"level":"HSK1","trad":"冷","simp":"冷","pinyin":"leng3","translation":"cold"},
    {"level":"HSK1","trad":"裡","simp":"里","pinyin":"li3","translation":"lining/interior/inside/internal/also written 裏|里[li3]"},
    {"level":"HSK1","trad":"零","simp":"零","pinyin":"ling2","translation":"zero/nought/zero sign/fractional/fragmentary/odd (of numbers)/(placed between two numbers to indicate a smaller quantity followed by a larger one)/fraction/(in mathematics) remainder (after division)/extra/to wither and fall/to wither"},
    {"level":"HSK1","trad":"六","simp":"六","pinyin":"liu4","translation":"six/6"},
    {"level":"HSK1","trad":"嗎","simp":"吗","pinyin":"ma5","translation":"(question particle for 'yes-no' questions)"},
    {"level":"HSK1","trad":"媽媽","simp":"妈妈","pinyin":"ma1 ma5","translation":"mama/mommy/mother/CL:個|个[ge4],位[wei4]"},
    {"level":"HSK1","trad":"買","simp":"买","pinyin":"mai3","translation":"to buy/to purchase"},
    {"level":"HSK1","trad":"貓","simp":"猫","pinyin":"mao1","translation":"cat/CL:隻|只[zhi1]/(dialect) to hide oneself/(coll.) modem"},
    {"level":"HSK1","trad":"沒","simp":"没","pinyin":"mei2","translation":"(negative prefix for verbs)/have not/not"},
    {"level":"HSK1","trad":"沒關係","simp":"没关系","pinyin":"mei2 guan1 xi5","translation":"it doesn't matter"},
    {"level":"HSK1","trad":"米飯","simp":"米饭","pinyin":"mi3 fan4","translation":"(cooked) rice"},
    {"level":"HSK1","trad":"明天","simp":"明天","pinyin":"ming2 tian1","translation":"tomorrow"},
    {"level":"HSK1","trad":"名字","simp":"名字","pinyin":"ming2 zi5","translation":"name (of a person or thing)/CL:個|个[ge4]"},
    {"level":"HSK1","trad":"那","simp":"那","pinyin":"na4","translation":"that/those/then (in that case)/commonly pr. [nei4] before a classifier, esp. in Beijing"},
    {"level":"HSK1","trad":"哪","simp":"哪","pinyin":"na3","translation":"how/which"},
    {"level":"HSK1","trad":"呢","simp":"呢","pinyin":"ne5","translation":"particle indicating that a previously asked question is to be applied to the preceding word ('What about ...?', 'And ...?')/particle for inquiring about location ('Where is ...?')/particle signaling a pause, to emphasize the preceding words and allow the listener time to take them on board ('ok?', 'are you with me?')/(at the end of a declarative sentence) particle indicating continuation of a state or action/particle indicating strong affirmation"},
    {"level":"HSK1","trad":"能","simp":"能","pinyin":"neng2","translation":"can/to be able to/might possibly/ability/(physics) energy"},
    {"level":"HSK1","trad":"你","simp":"你","pinyin":"ni3","translation":"you (informal, as opposed to courteous 您[nin2])"},
    {"level":"HSK1","trad":"年","simp":"年","pinyin":"nian2","translation":"year/CL:個|个[ge4]"},
    {"level":"HSK1","trad":"女兒","simp":"女儿","pinyin":"nu:3 er2","translation":"daughter"},
    {"level":"HSK1","trad":"朋友","simp":"朋友","pinyin":"peng2 you5","translation":"friend/CL:個|个[ge4],位[wei4]"},
    {"level":"HSK1","trad":"漂亮","simp":"漂亮","pinyin":"piao4 liang5","translation":"pretty/beautiful"},
    {"level":"HSK1","trad":"蘋果","simp":"苹果","pinyin":"ping2 guo3","translation":"apple/CL:個|个[ge4],顆|颗[ke1]"},
    {"level":"HSK1","trad":"七","simp":"七","pinyin":"qi1","translation":"seven/7"},
    {"level":"HSK1","trad":"錢","simp":"钱","pinyin":"qian2","translation":"coin/money/CL:筆|笔[bi3]/unit of weight, one tenth of a tael 兩|两[liang3]"},
    {"level":"HSK1","trad":"前面","simp":"前面","pinyin":"qian2 mian4","translation":"ahead/in front/preceding/above/also pr. [qian2 mian5]"},
    {"level":"HSK1","trad":"請","simp":"请","pinyin":"qing3","translation":"to ask/to invite/please (do sth)/to treat (to a meal etc)/to request"},
    {"level":"HSK1","trad":"去","simp":"去","pinyin":"qu4","translation":"to go/to go to (a place)/(of a time etc) last/just passed/to send/to remove/to get rid of/to reduce/to be apart from in space or time/to die (euphemism)/to play (a part)/(when used either before or after a verb) to go in order to do sth/(after a verb of motion indicates movement away from the speaker)/(used after certain verbs to indicate detachment or separation)"},
    {"level":"HSK1","trad":"熱","simp":"热","pinyin":"re4","translation":"to warm up/to heat up/hot (of weather)/heat/fervent"},
    {"level":"HSK1","trad":"人","simp":"人","pinyin":"ren2","translation":"man/person/people/CL:個|个[ge4],位[wei4]"},
    {"level":"HSK1","trad":"認識","simp":"认识","pinyin":"ren4 shi5","translation":"to know/to recognize/to be familiar with/to get acquainted with sb/knowledge/understanding/awareness/cognition"},
    {"level":"HSK1","trad":"日","simp":"日","pinyin":"ri4","translation":"sun/day/date, day of the month"},
    {"level":"HSK1","trad":"三","simp":"三","pinyin":"san1","translation":"three/3"},
    {"level":"HSK1","trad":"上","simp":"上","pinyin":"shang4","translation":"on top/upon/above/upper/previous/first (of multiple parts)/to climb/to get onto/to go up/to attend (class or university)"},
    {"level":"HSK1","trad":"商店","simp":"商店","pinyin":"shang1 dian4","translation":"store/shop/CL:家[jia1],個|个[ge4]"},
    {"level":"HSK1","trad":"上午","simp":"上午","pinyin":"shang4 wu3","translation":"morning/CL:個|个[ge4]"},
    {"level":"HSK1","trad":"少","simp":"少","pinyin":"shao3","translation":"few/less/to lack/to be missing/to stop (doing sth)/seldom"},
    {"level":"HSK1","trad":"誰","simp":"谁","pinyin":"shei2","translation":"who/also pr. [shui2]"},
    {"level":"HSK1","trad":"什麼","simp":"什么","pinyin":"shen2 me5","translation":"what?/who?/something/anything"},
    {"level":"HSK1","trad":"十","simp":"十","pinyin":"shi2","translation":"ten/10"},
    {"level":"HSK1","trad":"是","simp":"是","pinyin":"shi4","translation":"is/are/am/yes/to be"},
    {"level":"HSK1","trad":"時候","simp":"时候","pinyin":"shi2 hou5","translation":"time/length of time/moment/period"},
    {"level":"HSK1","trad":"書","simp":"书","pinyin":"shu1","translation":"book/letter/document/CL:本[ben3],冊|册[ce4],部[bu4]/to write"},
    {"level":"HSK1","trad":"水","simp":"水","pinyin":"shui3","translation":"water/river/liquid/beverage/additional charges or income/(of clothes) classifier for number of washes"},
    {"level":"HSK1","trad":"水果","simp":"水果","pinyin":"shui3 guo3","translation":"fruit/CL:個|个[ge4]"},
    {"level":"HSK1","trad":"睡覺","simp":"睡觉","pinyin":"shui4 jiao4","translation":"to go to bed/to sleep"},
    {"level":"HSK1","trad":"說話","simp":"说话","pinyin":"shuo1 hua4","translation":"to speak/to say/to talk/to gossip/to tell stories/talk/word"},
    {"level":"HSK1","trad":"四","simp":"四","pinyin":"si4","translation":"four/4"},
    {"level":"HSK1","trad":"嵗","simp":"岁","pinyin":"sui4","translation":"variant of 歲|岁[sui4], year/years old"},
    {"level":"HSK1","trad":"他","simp":"他","pinyin":"ta1","translation":"he or him/(used for either sex when the sex is unknown or unimportant)/(used before sb's name for emphasis)/(used as a meaningless mock object)/other/another"},
    {"level":"HSK1","trad":"她","simp":"她","pinyin":"ta1","translation":"she"},
    {"level":"HSK1","trad":"太","simp":"太","pinyin":"tai4","translation":"highest/greatest/too (much)/very/extremely"},
    {"level":"HSK1","trad":"天氣","simp":"天气","pinyin":"tian1 qi4","translation":"weather"},
    {"level":"HSK1","trad":"聽","simp":"听","pinyin":"ting1","translation":"to listen/to hear/to obey/a can (loanword from English 'tin')/classifier for canned beverages"},
    {"level":"HSK1","trad":"同學","simp":"同学","pinyin":"tong2 xue2","translation":"to study at the same school/fellow student/classmate/CL:位[wei4],個|个[ge4]"},
    {"level":"HSK1","trad":"喂","simp":"喂","pinyin":"wei2","translation":"hello (when answering the phone)"},
    {"level":"HSK1","trad":"我","simp":"我","pinyin":"wo3","translation":"I/me/my"},
    {"level":"HSK1","trad":"我們","simp":"我们","pinyin":"wo3 men5","translation":"we/us/ourselves/our"},
    {"level":"HSK1","trad":"五","simp":"五","pinyin":"wu3","translation":"five/5"},
    {"level":"HSK1","trad":"喜歡","simp":"喜欢","pinyin":"xi3 huan5","translation":"to like/to be fond of"},
    {"level":"HSK1","trad":"下","simp":"下","pinyin":"xia4","translation":"down/downwards/below/lower/later/next (week etc)/second (of two parts)/to decline/to go down/to arrive at (a decision, conclusion etc)/measure word to show the frequency of an action"},
    {"level":"HSK1","trad":"下午","simp":"下午","pinyin":"xia4 wu3","translation":"afternoon/CL:個|个[ge4]/p.m."},
    {"level":"HSK1","trad":"下雨","simp":"下雨","pinyin":"xia4 yu3","translation":"to rain"},
    {"level":"HSK1","trad":"先生","simp":"先生","pinyin":"Xian1 sheng5","translation":"Mister (Mr.)"},
    {"level":"HSK1","trad":"現在","simp":"现在","pinyin":"xian4 zai4","translation":"now/at present/at the moment/modern/current/nowadays"},
    {"level":"HSK1","trad":"想","simp":"想","pinyin":"xiang3","translation":"to think/to believe/to suppose/to wish/to want/to miss (feel wistful about the absence of sb or sth)"},
    {"level":"HSK1","trad":"小","simp":"小","pinyin":"xiao3","translation":"small/tiny/few/young"},
    {"level":"HSK1","trad":"小姐","simp":"小姐","pinyin":"xiao3 jie5","translation":"young lady/miss/(slang) prostitute/CL:個|个[ge4],位[wei4]"},
    {"level":"HSK1","trad":"寫","simp":"写","pinyin":"xie3","translation":"to write"},
    {"level":"HSK1","trad":"些","simp":"些","pinyin":"xie1","translation":"some/few/several/measure word indicating a small amount or small number (greater than 1)"},
    {"level":"HSK1","trad":"謝謝","simp":"谢谢","pinyin":"xie4 xie5","translation":"to thank/thanks/thank you"},
    {"level":"HSK1","trad":"星期","simp":"星期","pinyin":"xing1 qi1","translation":"week/CL:個|个[ge4]/day of the week/Sunday"},
    {"level":"HSK1","trad":"學生","simp":"学生","pinyin":"xue2 sheng5","translation":"student/schoolchild"},
    {"level":"HSK1","trad":"學習","simp":"学习","pinyin":"xue2 xi2","translation":"to learn/to study"},
    {"level":"HSK1","trad":"學校","simp":"学校","pinyin":"xue2 xiao4","translation":"school/CL:所[suo3]"},
    {"level":"HSK1","trad":"一","simp":"一","pinyin":"yi1","translation":"one/1/single/a (article)/as soon as/entire/whole/all/throughout/'one' radical in Chinese characters (Kangxi radical 1)/also pr. [yao1] for greater clarity when spelling out numbers digit by digit"},
    {"level":"HSK1","trad":"衣服","simp":"衣服","pinyin":"yi1 fu5","translation":"clothes/CL:件[jian4],套[tao4]"},
    {"level":"HSK1","trad":"醫生","simp":"医生","pinyin":"yi1 sheng1","translation":"doctor/CL:個|个[ge4],位[wei4],名[ming2]"},
    {"level":"HSK1","trad":"醫院","simp":"医院","pinyin":"yi1 yuan4","translation":"hospital/CL:所[suo3],家[jia1],座[zuo4]"},
    {"level":"HSK1","trad":"椅子","simp":"椅子","pinyin":"yi3 zi5","translation":"chair/CL:把[ba3],套[tao4]"},
    {"level":"HSK1","trad":"有","simp":"有","pinyin":"you3","translation":"to have/there is/there are/to exist/to be"},
    {"level":"HSK1","trad":"月","simp":"月","pinyin":"yue4","translation":"moon/month/monthly/CL:個|个[ge4],輪|轮[lun2]"},
    {"level":"HSK1","trad":"在","simp":"在","pinyin":"zai4","translation":"(located) at/(to be) in/to exist/in the middle of doing sth/(indicating an action in progress)"},
    {"level":"HSK1","trad":"再見","simp":"再见","pinyin":"zai4 jian4","translation":"goodbye/see you again later"},
    {"level":"HSK1","trad":"怎麼","simp":"怎么","pinyin":"zen3 me5","translation":"how?/what?/why?"},
    {"level":"HSK1","trad":"怎麼樣","simp":"怎么样","pinyin":"zen3 me5 yang4","translation":"how?/how about?/how was it?/how are things?"},
    {"level":"HSK1","trad":"這","simp":"这","pinyin":"zhe4","translation":"this/these/(commonly pr. [zhei4] before a classifier, esp. in Beijing)"},
    {"level":"HSK1","trad":"中國","simp":"中国","pinyin":"Zhong1 guo2","translation":"China"},
    {"level":"HSK1","trad":"中午","simp":"中午","pinyin":"zhong1 wu3","translation":"noon/midday/CL:個|个[ge4]"},
    {"level":"HSK1","trad":"住","simp":"住","pinyin":"zhu4","translation":"to live/to dwell/to stay/to reside/to stop/(suffix indicating firmness, steadiness, or coming to a halt)"},
    {"level":"HSK1","trad":"桌子","simp":"桌子","pinyin":"zhuo1 zi5","translation":"table/desk/CL:張|张[zhang1],套[tao4]"},
    {"level":"HSK1","trad":"字","simp":"字","pinyin":"zi4","translation":"letter/symbol/character/word/CL:個|个[ge4]/courtesy or style name traditionally given to males aged 20 in dynastic China"},
    {"level":"HSK1","trad":"做","simp":"做","pinyin":"zuo4","translation":"to do/to make/to produce/to write/to compose/to act as/to engage in/to hold (a party)/to be/to become/to function (in some capacity)/to serve as/to be used for/to form (a bond or relationship)/to pretend/to feign/to act a part/to put on appearance"},
    {"level":"HSK1","trad":"坐","simp":"坐","pinyin":"zuo4","translation":"to sit/to take a seat/to take (a bus, airplane etc)/to bear fruit/variant of 座[zuo4]"},
    {"level":"HSK1","trad":"昨天","simp":"昨天","pinyin":"zuo2 tian1","translation":"yesterday"},
    {"level":"HSK2","trad":"吧","simp":"吧","pinyin":"ba5","translation":"(modal particle indicating suggestion or surmise)/...right?/...OK?/...I presume."},
    {"level":"HSK2","trad":"白","simp":"白","pinyin":"bai2","translation":"white/snowy/pure/bright/empty/blank/plain/clear/to make clear/in vain/gratuitous/free of charge/reactionary/anti-communist/funeral/to stare coldly/to write wrong character/to state/to explain/vernacular/spoken lines in opera"},
    {"level":"HSK2","trad":"百","simp":"百","pinyin":"bai3","translation":"hundred/numerous/all kinds of"},
    {"level":"HSK2","trad":"幫助","simp":"帮助","pinyin":"bang1 zhu4","translation":"assistance/aid/to help/to assist"},
    {"level":"HSK2","trad":"報紙","simp":"报纸","pinyin":"bao4 zhi3","translation":"newspaper/newsprint/CL:份[fen4],期[qi1],張|张[zhang1]"},
    {"level":"HSK2","trad":"比","simp":"比","pinyin":"bi3","translation":"(particle used for comparison and '-er than')/to compare/to contrast/to gesture (with hands)/ratio"},
    {"level":"HSK2","trad":"別","simp":"别","pinyin":"bie2","translation":"to leave/to depart/to separate/to distinguish/to classify/other/another/don't ...!/to pin/to stick (sth) in"},
    {"level":"HSK2","trad":"長","simp":"长","pinyin":"chang2","translation":"length/long/forever/always/constantly"},
    {"level":"HSK2","trad":"唱歌","simp":"唱歌","pinyin":"chang4 ge1","translation":"to sing a song"},
    {"level":"HSK2","trad":"出","simp":"出","pinyin":"chu1","translation":"to go out/to come out/to occur/to produce/to go beyond/to rise/to put forth/to happen/(used after a verb to indicate an outward direction or a positive result)/classifier for dramas, plays, operas etc"},
    {"level":"HSK2","trad":"船","simp":"船","pinyin":"chuan2","translation":"boat/vessel/ship/CL:條|条[tiao2],艘[sou1],隻|只[zhi1]"},
    {"level":"HSK2","trad":"穿","simp":"穿","pinyin":"chuan1","translation":"to wear/to put on/to dress/to bore through/to pierce/to perforate/to penetrate/to pass through/to thread"},
    {"level":"HSK2","trad":"次","simp":"次","pinyin":"ci4","translation":"next in sequence/second/the second (day, time etc)/secondary/vice-/sub-/infra-/inferior quality/substandard/order/sequence/hypo- (chemistry)/classifier for enumerated events: time"},
    {"level":"HSK2","trad":"從","simp":"从","pinyin":"cong2","translation":"from/through/via/to follow/to obey/to engage in (an activity)/never (in negative sentence)/(Taiwan pr. [zong4]) retainer/assistant/accomplice/related by common paternal grandfather or earlier ancestor"},
    {"level":"HSK2","trad":"錯","simp":"错","pinyin":"cuo4","translation":"mistake/wrong/bad/interlocking/complex/to grind/to polish/to alternate/to stagger/to miss/to let slip/to evade/to inlay with gold or silver"},
    {"level":"HSK2","trad":"大家","simp":"大家","pinyin":"da4 jia1","translation":"everyone/influential family/great expert"},
    {"level":"HSK2","trad":"打籃球","simp":"打篮球","pinyin":"da3 lan2 qiu2","translation":"to play basketball"},
    {"level":"HSK2","trad":"但是","simp":"但是","pinyin":"dan4 shi4","translation":"but/however"},
    {"level":"HSK2","trad":"到","simp":"到","pinyin":"dao4","translation":"to (a place)/until (a time)/up to/to go/to arrive/(verb complement denoting completion or result of an action)"},
    {"level":"HSK2","trad":"得","simp":"得","pinyin":"de5","translation":"structural particle: used after a verb (or adjective as main verb), linking it to following phrase indicating effect, degree, possibility etc"},
    {"level":"HSK2","trad":"等","simp":"等","pinyin":"deng3","translation":"class/rank/grade/equal to/same as/to wait for/to await/et cetera/and so on/et al. (and other authors)/after/as soon as/once"},
    {"level":"HSK2","trad":"弟弟","simp":"弟弟","pinyin":"di4 di5","translation":"younger brother/CL:個|个[ge4],位[wei4]"},
    {"level":"HSK2","trad":"第一","simp":"第一","pinyin":"di4 yi1","translation":"first/number one/primary"},
    {"level":"HSK2","trad":"懂","simp":"懂","pinyin":"dong3","translation":"to understand/to comprehend"},
    {"level":"HSK2","trad":"對","simp":"对","pinyin":"dui4","translation":"right/correct/couple/pair/towards/at/for/to face/opposite/to treat (sb a certain way)/to match together/to adjust/to fit/to suit/to answer/to reply/classifier: couple"},
    {"level":"HSK2","trad":"房間","simp":"房间","pinyin":"fang2 jian1","translation":"room/CL:間|间[jian1],個|个[ge4]"},
    {"level":"HSK2","trad":"非常","simp":"非常","pinyin":"fei1 chang2","translation":"very/very much/unusual/extraordinary"},
    {"level":"HSK2","trad":"服務員","simp":"服务员","pinyin":"fu2 wu4 yuan2","translation":"waiter/waitress/attendant/customer service personnel/CL:個|个[ge4],位[wei4]"},
    {"level":"HSK2","trad":"高","simp":"高","pinyin":"gao1","translation":"high/tall/above average/loud/your (honorific)"},
    {"level":"HSK2","trad":"告訴","simp":"告诉","pinyin":"gao4 su5","translation":"to tell/to inform/to let know"},
    {"level":"HSK2","trad":"哥哥","simp":"哥哥","pinyin":"ge1 ge5","translation":"older brother/CL:個|个[ge4],位[wei4]"},
    {"level":"HSK2","trad":"給","simp":"给","pinyin":"gei3","translation":"to/for/for the benefit of/to give/to allow/to do sth (for sb)/(grammatical equivalent of 被)/(grammatical equivalent of 把)/(sentence intensifier)"},
    {"level":"HSK2","trad":"公共汽車","simp":"公共汽车","pinyin":"gong1 gong4 qi4 che1","translation":"bus/CL:輛|辆[liang4],班[ban1]"},
    {"level":"HSK2","trad":"公斤","simp":"公斤","pinyin":"gong1 jin1","translation":"kilogram (kg)"},
    {"level":"HSK2","trad":"公司","simp":"公司","pinyin":"gong1 si1","translation":"(business) company/company/firm/corporation/incorporated/CL:家[jia1]"},
    {"level":"HSK2","trad":"貴","simp":"贵","pinyin":"gui4","translation":"expensive/noble/precious/(honorific) your"},
    {"level":"HSK2","trad":"過","simp":"过","pinyin":"guo5","translation":"(experienced action marker)"},
    {"level":"HSK2","trad":"還","simp":"还","pinyin":"hai2","translation":"still/still in progress/still more/yet/even more/in addition/fairly/passably (good)/as early as/even/also/else"},
    {"level":"HSK2","trad":"孩子","simp":"孩子","pinyin":"hai2 zi5","translation":"child"},
    {"level":"HSK2","trad":"號","simp":"号","pinyin":"hao4","translation":"ordinal number/day of a month/mark/sign/business establishment/size/ship suffix/horn (wind instrument)/bugle call/assumed name/to take a pulse/classifier used to indicate number of people"},
    {"level":"HSK2","trad":"好吃","simp":"好吃","pinyin":"hao3 chi1","translation":"tasty/delicious"},
    {"level":"HSK2","trad":"黑","simp":"黑","pinyin":"hei1","translation":"black/dark/sinister/secret/shady/illegal/to hide (sth) away/to vilify/(loanword) to hack (computing)"},
    {"level":"HSK2","trad":"紅","simp":"红","pinyin":"hong2","translation":"red/popular/revolutionary/bonus"},
    {"level":"HSK2","trad":"歡迎","simp":"欢迎","pinyin":"huan1 ying2","translation":"to welcome/welcome"},
    {"level":"HSK2","trad":"回答","simp":"回答","pinyin":"hui2 da2","translation":"to reply/to answer/the answer/CL:個|个[ge4]"},
    {"level":"HSK2","trad":"機場","simp":"机场","pinyin":"ji1 chang3","translation":"airport/airfield/CL:家[jia1],處|处[chu4]"},
    {"level":"HSK2","trad":"雞蛋","simp":"鸡蛋","pinyin":"ji1 dan4","translation":"(chicken) egg/hen's egg/CL:個|个[ge4],打[da2]"},
    {"level":"HSK2","trad":"件","simp":"件","pinyin":"jian4","translation":"item/component/classifier for events, things, clothes etc"},
    {"level":"HSK2","trad":"教室","simp":"教室","pinyin":"jiao4 shi4","translation":"classroom/CL:間|间[jian1]"},
    {"level":"HSK2","trad":"姐姐","simp":"姐姐","pinyin":"jie3 jie5","translation":"older sister/CL:個|个[ge4]"},
    {"level":"HSK2","trad":"介紹","simp":"介绍","pinyin":"jie4 shao4","translation":"to introduce (sb to sb)/to give a presentation/to present (sb for a job etc)/introduction"},
    {"level":"HSK2","trad":"進","simp":"进","pinyin":"jin4","translation":"to go forward/to advance/to go in/to enter/to put in/to submit/to take in/to admit/(math.) base of a number system/classifier for sections in a building or residential compound"},
    {"level":"HSK2","trad":"近","simp":"近","pinyin":"jin4","translation":"near/close to/approximately"},
    {"level":"HSK2","trad":"就","simp":"就","pinyin":"jiu4","translation":"at once/right away/only/just (emphasis)/as early as/already/as soon as/then/in that case/as many as/even if/to approach/to move towards/to undertake/to engage in/to suffer/subjected to/to accomplish/to take advantage of/to go with (of foods)/with regard to/concerning"},
    {"level":"HSK2","trad":"覺得","simp":"觉得","pinyin":"jue2 de5","translation":"to think/to feel"},
    {"level":"HSK2","trad":"咖啡","simp":"咖啡","pinyin":"ka1 fei1","translation":"coffee (loanword)/CL:杯[bei1]"},
    {"level":"HSK2","trad":"開始","simp":"开始","pinyin":"kai1 shi3","translation":"to begin/beginning/to start/initial/CL:個|个[ge4]"},
    {"level":"HSK2","trad":"考試","simp":"考试","pinyin":"kao3 shi4","translation":"to take an exam/exam/CL:次[ci4]"},
    {"level":"HSK2","trad":"課","simp":"课","pinyin":"ke4","translation":"subject/course/CL:門|门[men2]/class/lesson/CL:堂[tang2],節|节[jie2]/to levy/tax/form of divination"},
    {"level":"HSK2","trad":"可能","simp":"可能","pinyin":"ke3 neng2","translation":"might (happen)/possible/probable/possibility/probability/maybe/perhaps/CL:個|个[ge4]"},
    {"level":"HSK2","trad":"可以","simp":"可以","pinyin":"ke3 yi3","translation":"can/may/possible/able to/not bad/pretty good"},
    {"level":"HSK2","trad":"快","simp":"快","pinyin":"kuai4","translation":"rapid/quick/speed/rate/soon/almost/to make haste/clever/sharp (of knives or wits)/forthright/plainspoken/gratified/pleased/pleasant"},
    {"level":"HSK2","trad":"快樂","simp":"快乐","pinyin":"kuai4 le4","translation":"happy/merry"},
    {"level":"HSK2","trad":"累","simp":"累","pinyin":"lei4","translation":"tired/weary/to strain/to wear out/to work hard"},
    {"level":"HSK2","trad":"離","simp":"离","pinyin":"li2","translation":"to leave/to part from/to be away from/(in giving distances) from/without (sth)/independent of/one of the Eight Trigrams 八卦[ba1 gua4], symbolizing fire/☲"},
    {"level":"HSK2","trad":"兩","simp":"两","pinyin":"liang3","translation":"two/both/some/a few/tael, unit of weight equal to 50 grams (modern) or 1⁄16 of a catty 斤[jin1] (old)"},
    {"level":"HSK2","trad":"路","simp":"路","pinyin":"lu4","translation":"road/CL:條|条[tiao2]/journey/route/line (bus etc)/sort/kind"},
    {"level":"HSK2","trad":"旅遊","simp":"旅游","pinyin":"lu:3 you2","translation":"trip/journey/tourism/travel/tour/to travel"},
    {"level":"HSK2","trad":"賣","simp":"卖","pinyin":"mai4","translation":"to sell/to betray/to spare no effort/to show off or flaunt"},
    {"level":"HSK2","trad":"慢","simp":"慢","pinyin":"man4","translation":"slow"},
    {"level":"HSK2","trad":"忙","simp":"忙","pinyin":"mang2","translation":"busy/hurriedly/to hurry/to rush"},
    {"level":"HSK2","trad":"每","simp":"每","pinyin":"mei3","translation":"each/every"},
    {"level":"HSK2","trad":"妹妹","simp":"妹妹","pinyin":"mei4 mei5","translation":"younger sister/young woman/CL:個|个[ge4]"},
    {"level":"HSK2","trad":"門","simp":"门","pinyin":"men2","translation":"gate/door/CL:扇[shan4]/gateway/doorway/CL:個|个[ge4]/opening/valve/switch/way to do something/knack/family/house/(religious) sect/school (of thought)/class/category/phylum or division (taxonomy)/classifier for large guns/classifier for lessons, subjects, branches of technology/(suffix) -gate (i.e. scandal; derived from Watergate)"},
    {"level":"HSK2","trad":"男人","simp":"男人","pinyin":"nan2 ren2","translation":"a man/a male/men/CL:個|个[ge4]"},
    {"level":"HSK2","trad":"您","simp":"您","pinyin":"nin2","translation":"you (courteous, as opposed to informal 你[ni3])"},
    {"level":"HSK2","trad":"牛奶","simp":"牛奶","pinyin":"niu2 nai3","translation":"cow's milk/CL:瓶[ping2],杯[bei1]"},
    {"level":"HSK2","trad":"女人","simp":"女人","pinyin":"nu:3 ren2","translation":"woman"},
    {"level":"HSK2","trad":"旁邊","simp":"旁边","pinyin":"pang2 bian1","translation":"lateral/side/to the side/beside"},
    {"level":"HSK2","trad":"跑步","simp":"跑步","pinyin":"pao3 bu4","translation":"to run/to jog/(military) to march at the double"},
    {"level":"HSK2","trad":"便宜","simp":"便宜","pinyin":"pian2 yi5","translation":"cheap/inexpensive/small advantages/to let sb off lightly"},
    {"level":"HSK2","trad":"票","simp":"票","pinyin":"piao4","translation":"ticket/ballot/banknote/CL:張|张[zhang1]/person held for ransom/amateur performance of Chinese opera/classifier for groups, batches, business transactions"},
    {"level":"HSK2","trad":"起床","simp":"起床","pinyin":"qi3 chuang2","translation":"to get out of bed/to get up"},
    {"level":"HSK2","trad":"妻子","simp":"妻子","pinyin":"qi1 zi3","translation":"wife and children"},
    {"level":"HSK2","trad":"千","simp":"千","pinyin":"qian1","translation":"thousand"},
    {"level":"HSK2","trad":"晴","simp":"晴","pinyin":"qing2","translation":"clear/fine (weather)"},
    {"level":"HSK2","trad":"去年","simp":"去年","pinyin":"qu4 nian2","translation":"last year"},
    {"level":"HSK2","trad":"讓","simp":"让","pinyin":"rang4","translation":"to yield/to permit/to let sb do sth/to have sb do sth/to make sb (feel sad etc)/by (indicates the agent in a passive clause, like 被[bei4])"},
    {"level":"HSK2","trad":"上班","simp":"上班","pinyin":"shang4 ban1","translation":"to go to work/to be on duty/to start work/to go to the office"},
    {"level":"HSK2","trad":"身體","simp":"身体","pinyin":"shen1 ti3","translation":"the body/one's health/CL:具[ju4],個|个[ge4]/in person"},
    {"level":"HSK2","trad":"生病","simp":"生病","pinyin":"sheng1 bing4","translation":"to fall ill"},
    {"level":"HSK2","trad":"生日","simp":"生日","pinyin":"sheng1 ri4","translation":"birthday/CL:個|个[ge4]"},
    {"level":"HSK2","trad":"時間","simp":"时间","pinyin":"shi2 jian1","translation":"time/period/CL:段[duan4]"},
    {"level":"HSK2","trad":"事情","simp":"事情","pinyin":"shi4 qing5","translation":"affair/matter/thing/business/CL:件[jian4],樁|桩[zhuang1]"},
    {"level":"HSK2","trad":"手錶","simp":"手表","pinyin":"shou3 biao3","translation":"wrist watch/CL:塊|块[kuai4],隻|只[zhi1],個|个[ge4]"},
    {"level":"HSK2","trad":"手機","simp":"手机","pinyin":"shou3 ji1","translation":"cell phone/mobile phone/CL:部[bu4],支[zhi1]"},
    {"level":"HSK2","trad":"送","simp":"送","pinyin":"song4","translation":"to deliver/to carry/to give (as a present)/to present (with)/to see off/to send"},
    {"level":"HSK2","trad":"所以","simp":"所以","pinyin":"suo3 yi3","translation":"therefore/as a result/so/the reason why"},
    {"level":"HSK2","trad":"它","simp":"它","pinyin":"ta1","translation":"it"},
    {"level":"HSK2","trad":"題","simp":"题","pinyin":"ti2","translation":"topic/problem for discussion/exam question/subject/to inscribe/to mention/CL:個|个[ge4],道[dao4]"},
    {"level":"HSK2","trad":"踢足球","simp":"踢足球","pinyin":"ti1 zu2 qiu2","translation":"to play soccer"},
    {"level":"HSK2","trad":"跳舞","simp":"跳舞","pinyin":"tiao4 wu3","translation":"to dance"},
    {"level":"HSK2","trad":"外","simp":"外","pinyin":"wai4","translation":"outside/in addition/foreign/external"},
    {"level":"HSK2","trad":"完","simp":"完","pinyin":"wan2","translation":"to finish/to be over/whole/complete/entire"},
    {"level":"HSK2","trad":"玩","simp":"玩","pinyin":"wan2","translation":"to play/to have fun/to trifle with/toy/sth used for amusement/curio or antique (Taiwan pr. [wan4])/to keep sth for entertainment"},
    {"level":"HSK2","trad":"晚上","simp":"晚上","pinyin":"wan3 shang5","translation":"evening/night/CL:個|个[ge4]/in the evening"},
    {"level":"HSK2","trad":"為什麼","simp":"为什么","pinyin":"wei4 shen2 me5","translation":"why?/for what reason?"},
    {"level":"HSK2","trad":"問","simp":"问","pinyin":"wen4","translation":"to ask"},
    {"level":"HSK2","trad":"問題","simp":"问题","pinyin":"wen4 ti2","translation":"question/problem/issue/topic/CL:個|个[ge4]"},
    {"level":"HSK2","trad":"洗","simp":"洗","pinyin":"xi3","translation":"to wash/to bathe/to develop (photo)"},
    {"level":"HSK2","trad":"西瓜","simp":"西瓜","pinyin":"xi1 gua1","translation":"watermelon/CL:顆|颗[ke1],粒[li4],個|个[ge5]"},
    {"level":"HSK2","trad":"希望","simp":"希望","pinyin":"xi1 wang4","translation":"to wish for/to desire/hope/CL:個|个[ge4]"},
    {"level":"HSK2","trad":"向","simp":"向","pinyin":"xiang4","translation":"towards/to face/to turn towards/direction/to support/to side with/shortly before/formerly/always/all along"},
    {"level":"HSK2","trad":"笑","simp":"笑","pinyin":"xiao4","translation":"laugh/smile/CL:個|个[ge4]"},
    {"level":"HSK2","trad":"小時","simp":"小时","pinyin":"xiao3 shi2","translation":"hour/CL:個|个[ge4]"},
    {"level":"HSK2","trad":"新","simp":"新","pinyin":"xin1","translation":"new/newly/meso- (chemistry)"},
    {"level":"HSK2","trad":"姓","simp":"姓","pinyin":"xing4","translation":"family name/surname/CL:個|个[ge4]/to be surnamed"},
    {"level":"HSK2","trad":"休息","simp":"休息","pinyin":"xiu1 xi5","translation":"rest/to rest"},
    {"level":"HSK2","trad":"雪","simp":"雪","pinyin":"xue3","translation":"snow/snowfall/CL:場|场[chang2]/to have the appearance of snow/to wipe away, off or out/to clean"},
    {"level":"HSK2","trad":"眼睛","simp":"眼睛","pinyin":"yan3 jing5","translation":"eye/CL:隻|只[zhi1],雙|双[shuang1]"},
    {"level":"HSK2","trad":"顏色","simp":"颜色","pinyin":"yan2 se4","translation":"color/countenance/appearance/facial expression/pigment/dyestuff"},
    {"level":"HSK2","trad":"羊肉","simp":"羊肉","pinyin":"yang2 rou4","translation":"mutton/goat meat"},
    {"level":"HSK2","trad":"藥","simp":"药","pinyin":"yao4","translation":"medicine/drug/substance used for a specific purpose (e.g. poisoning, explosion, fermenting)/CL:種|种[zhong3],服[fu4],味[wei4]/to poison"},
    {"level":"HSK2","trad":"要","simp":"要","pinyin":"yao1","translation":"to demand/to request/to coerce"},
    {"level":"HSK2","trad":"也","simp":"也","pinyin":"ye3","translation":"also/too/(in Classical Chinese) final particle implying affirmation"},
    {"level":"HSK2","trad":"已經","simp":"已经","pinyin":"yi3 jing1","translation":"already"},
    {"level":"HSK2","trad":"一起","simp":"一起","pinyin":"yi1 qi3","translation":"in the same place/together/with/altogether (in total)"},
    {"level":"HSK2","trad":"意思","simp":"意思","pinyin":"yi4 si5","translation":"idea/opinion/meaning/wish/desire/interest/fun/token of appreciation, affection etc/CL:個|个[ge4]/to give as a small token/to do sth as a gesture of goodwill etc"},
    {"level":"HSK2","trad":"陰","simp":"阴","pinyin":"yin1","translation":"overcast (weather)/cloudy/shady/Yin (the negative principle of Yin and Yang)/negative (electric.)/feminine/moon/implicit/hidden/genitalia"},
    {"level":"HSK2","trad":"因為","simp":"因为","pinyin":"yin1 wei4","translation":"because/owing to/on account of"},
    {"level":"HSK2","trad":"右邊","simp":"右边","pinyin":"you4 bian5","translation":"right side/right, to the right"},
    {"level":"HSK2","trad":"游泳","simp":"游泳","pinyin":"you2 yong3","translation":"swimming/to swim"},
    {"level":"HSK2","trad":"魚","simp":"鱼","pinyin":"yu2","translation":"fish/CL:條|条[tiao2],尾[wei3]"},
    {"level":"HSK2","trad":"元","simp":"元","pinyin":"yuan2","translation":"currency unit (esp. Chinese yuan)/first/original/primary/fundamental/constituent/part/era (of a reign)/meta- (prefix)/(math.) argument/variable/(Tw) (geology) eon"},
    {"level":"HSK2","trad":"遠","simp":"远","pinyin":"yuan3","translation":"far/distant/remote/(intensifier in a comparison) by far/much (lower etc)"},
    {"level":"HSK2","trad":"運動","simp":"运动","pinyin":"yun4 dong4","translation":"to move/to exercise/sports/exercise/motion/movement/campaign/CL:場|场[chang3]"},
    {"level":"HSK2","trad":"再","simp":"再","pinyin":"zai4","translation":"again/once more/re-/second/another/then (after sth, and not until then)"},
    {"level":"HSK2","trad":"早上","simp":"早上","pinyin":"zao3 shang5","translation":"early morning/CL:個|个[ge4]"},
    {"level":"HSK2","trad":"張","simp":"张","pinyin":"zhang1","translation":"to open up/to spread/sheet of paper/classifier for flat objects, sheet/classifier for votes"},
    {"level":"HSK2","trad":"丈夫","simp":"丈夫","pinyin":"zhang4 fu5","translation":"husband/CL:個|个[ge4]"},
    {"level":"HSK2","trad":"找","simp":"找","pinyin":"zhao3","translation":"to try to find/to look for/to call on sb/to find/to seek/to return/to give change"},
    {"level":"HSK2","trad":"著","simp":"着","pinyin":"zhe5","translation":"aspect particle indicating action in progress"},
    {"level":"HSK2","trad":"真","simp":"真","pinyin":"zhen1","translation":"really/truly/indeed/real/true/genuine"},
    {"level":"HSK2","trad":"正在","simp":"正在","pinyin":"zheng4 zai4","translation":"just at (that time)/right in (that place)/right in the middle of (doing sth)"},
    {"level":"HSK2","trad":"知道","simp":"知道","pinyin":"zhi1 dao4","translation":"to know/to become aware of/also pr. [zhi1 dao5]"},
    {"level":"HSK2","trad":"準備","simp":"准备","pinyin":"zhun3 bei4","translation":"preparation/to prepare/to intend/to be about to/reserve (fund)"},
    {"level":"HSK2","trad":"自行車","simp":"自行车","pinyin":"zi4 xing2 che1","translation":"bicycle/bike/CL:輛|辆[liang4]"},
    {"level":"HSK2","trad":"走","simp":"走","pinyin":"zou3","translation":"to walk/to go/to run/to move (of vehicle)/to visit/to leave/to go away/to die (euph.)/from/through/away (in compound verbs, such as 撤走[che4 zou3])/to change (shape, form, meaning)"},
    {"level":"HSK2","trad":"最","simp":"最","pinyin":"zui4","translation":"most/the most/-est (superlative suffix)"},
    {"level":"HSK2","trad":"左邊","simp":"左边","pinyin":"zuo3 bian5","translation":"left/the left side/to the left of"}
  ]


  HSK1.remove({});

  for(var hsk1v in hsk1voc){
    HSK1.insert(hsk1voc[hsk1v]);
  }

}
